## TMUX.CONF ##

# key bindings 
unbind C-b
set -g prefix C-a
bind-key Space choose-window
bind-key C-a last-window

######################
### DESIGN CHANGES ###
######################

set -g mouse off

# panes
set -g pane-border-fg black
set -g pane-active-border-fg brightred

## Status bar design
# status line
set -g status-justify centre 
#set -g status-bg default
#set -g status-fg white
set -g status-interval 1

#setw automatic-rename 
#setw allow-rename on 

#window mode
setw -g mode-bg colour6
setw -g mode-fg colour0

# window status
set-window-option -g window-status-current-att none
set-window-option -g window-status-current-bg default

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
setw -g monitor-activity on
set-window -g monitor-activity on
set-window-option -g window-status-activity-fg red
set-window-option -g window-status-activity-bg default
set-window-option -g window-status-activity-attr none
#set -g window-status-activity-format "#[fg=red,none,bg=default]#I#[fg=white,bg=default]:#[fg=colour251,bg=default]"

set -g default-terminal "screen-256color"

# The modes {
setw -g clock-mode-colour colour12
setw -g mode-attr bold
setw -g mode-fg colour3
setw -g mode-bg colour238

# }
# The panes {

set -g pane-border-bg default
set -g pane-border-fg colour7
set -g pane-active-border-bg default
set -g pane-active-border-fg colour239

# }
# The statusbar {

set -g status-position bottom
set -g status-bg default
set -g status-fg colour7
#set -g status-attr dim
set -g status-left ''
set -g status-right '' 
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-fg colour7
setw -g window-status-current-bg default 
setw -g window-status-current-attr none
#setw -g window-status-current-format '  #[fg=colour2]#F#[fg=colour242]#I#[fg=colour242]|#[fg=colour3]#(echo "#{pane_current_path}" | rev | cut -d'/' -f-3 | rev)#[fg=colour2]#F  '
setw -g window-status-current-format '#[fg=colour242]#I#[fg=colour2]#F #[fg=colour3]#W'

setw -g window-status-fg colour7
setw -g window-status-bg default
setw -g window-status-attr none
#setw -g window-status-format '#[fg=colour242]| #[fg=colour3]#I #[fg=colour2]#F#[fg=colour4]#(echo "#{pane_current_path}" | rev | cut -d'/' -f-3 | rev)#[fg=colour242] | '
setw -g window-status-format '#[fg=colour242]| #[fg=colour3]#I #[fg=colour2]#F#[fg=colour4]#W #[fg=colour242] | '

bind-key k rename-window "#(echo #{pane_current_path} | rev | cut -d'/' -f-3 | rev)"

setw -g window-status-bell-attr bold
setw -g window-status-bell-fg colour255
setw -g window-status-bell-bg colour1

# }
# The messages {

set -g message-attr bold
set -g message-fg colour3
set -g message-bg colour14

# }


##################
## PANE OPTIONS ##
##################

set -g base-index 1
 
# cycle 
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# split
bind-key - split-window -v # split pane horizontally ->  ----
bind-key = split-window -h # split pane vertically   ->   |

# break = break split pane out to its own
bind-key Enter break-pane

##########
## MISC ##
##########

#set -sa terminal-overrides ",*:dim=\\E[2m"

# basic
set-window-option -g xterm-keys on

# scrollback history 
set-option -g history-limit 5000

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config-reloaded!!!"

# messaging 
set -g message-fg red
set -g message-bg default
set -g message-attr bold

